version: '3'
services:
  postgres:
    image: postgres
    hostname: postgres
    ports:
      - "6543:5432"
    env_file:
      - database.env # configure postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  sinatra:
    build: .
    depends_on:
      - postgres
    ports:
      - "80:4567"
    

volumes:
  postgres-data: